### ISSUE TITLE
MI5X Kamera Sorunu

### ISSUE THREAD

**Issue by cantekinerdogan** [suat074/MA-XML-10-TURKISH#1]
Merhaba,

Sorumlular değişmiş ve eski sayfa silinmiş olduğu için tekrar yazıyorum. 8.8.16 romunda portre modunda fotoğraf çekip normal fotoğraf moduna geldiğinizde normal moddaki ilk fotoğraf bozuk çekiliyor. Gereksiz bir zoom yapıyor fotoya. Kamerayı sifirladiginizda düzeliyor ama 16-9 moduna aldığınızda tekrar sorun devam ediyor.

Teşekkürler.

**Comment by cantekinerdogan** [comment]
8.8.23 de de aynı problem var.

**Comment by rabilgic** [comment]
Bu tarz bug bildirimlerini lütfen https://xiaomi.eu/community/forums/bugs.20/ foruma bildiriniz. Çeviri ile ilgili sorunlarını buradan bizlere bildirebilirsiniz. Teşekkürler.
