### ISSUE TITLE
temalar kısmı

### ISSUE THREAD

**Issue by gugukcu** [suat074/MA-XML-10-TURKISH#10]
temalar kısmında klasik miui 10 teması yok. default olarak olan seçenekte ikonlar klasikten farklı. resmi romda klasik miui 10 teması vardı.

**Comment by rabilgic** [comment]
Rom ile ilgili bildiri ve isteklerinizi xiaomi.eu forumu üzerinden ilgili bölüme konu açarak bildirebilirsiniz. Teşekkürler.
