### ISSUE TITLE
Profil Videosu Denen Kısım

### ISSUE THREAD

**Issue by Teknoist** [suat074/MA-XML-10-TURKISH#11]
Sanirim yeni bir kısım eklenmiş profil Videosu hem orda bir çevrilmemiş bölüm var birde gösterilen canlı duvar kagidindan seçim yaptirmiyor. MI6 cihazım son sürüm yüklü 9.3.21
https://i.hizliresim.com/alrEBQ.png

**Comment by suatsari** [comment]
Geri bildirim için teşekkürler. Düzeltildi
