### ISSUE TITLE
mi5 Google play sorunu

### ISSUE THREAD

**Issue by marcodivaio9** [suat074/MA-XML-10-TURKISH#13]
Hocam Mi5 te eu beta son güncellemede google playden bir şey indirip, var olan uygulama güncelleyemiyorum. Yapmadığım işlem kalmadı. Yardımcı olurmusunuz.

**Comment by rabilgic** [comment]
Durum hakkında xiaomi.eu forumundan destek alabilirsiniz.

**Comment by marcodivaio9** [comment]
Hard Reset atarak sorunu çözdüm. İlginiz için teşekkürler.
