### ISSUE TITLE
MI5X Ses Sorunu

### ISSUE THREAD

**Issue by cantekinerdogan** [suat074/MA-XML-10-TURKISH#2]
Merhaba,

8.8.16 romunda karşı tarafın sesi çok az geliyor. Modem dosyasında bir problem olduğunu düşünüyorum.

**Comment by rabilgic** [comment]
Bu tarz bug bildirimlerini lütfen https://xiaomi.eu/community/forums/bugs.20/ foruma bildiriniz. Çeviri ile ilgili sorunlarını buradan bizlere bildirebilirsiniz. Teşekkürler.
