### ISSUE TITLE
redmi 6 pro

### ISSUE THREAD

**Issue by loof93** [suat074/MA-XML-10-TURKISH#3]
iyi günler.Redmi 6 pro bildirimler ekranın üst köşesinde ikon olarak belirmiyor.Güncellemede düzeltildiğini görülüyor fakat düzeltilmemiş.tşkler.

**Comment by rabilgic** [comment]
Bu tarz bug bildirimlerini lütfen https://xiaomi.eu/community/forums/bugs.20/ foruma bildiriniz. Çeviri ile ilgili sorunlarını buradan bizlere bildirebilirsiniz. Teşekkürler.
