### ISSUE TITLE
8.11.22

### ISSUE THREAD

**Issue by cantekinerdogan** [suat074/MA-XML-10-TURKISH#4]
Suat hocam merhabalar.

MI5X kullanıyorum. Son uygulamalar ekranına yeni eklenen butonlar İngilizce kalmış.
![screenshot_2018-11-24-22-17-20-513_com android systemui](https://user-images.githubusercontent.com/25240661/48972426-1d4b2200-f03b-11e8-8f1b-072b589e64ff.png)

**Comment by suat074** [comment]
Orası Perşembe günü çevrildi, ama repoya yetişmedi. Gelecek sürümde düzelecektir...
