### ISSUE TITLE
mi 6x sms yollama sorunu

### ISSUE THREAD

**Issue by mustafaaytar4807** [suat074/MA-XML-10-TURKISH#6]
sms uygulamasına girince manuel numara girişi yok 4 tane rehberden numara çıkıyor onlar harici numara seçilmiyor ve elle numara girişi mevcut değil. sms yollamak için arama kaydı sayfasından numaraya tıklayıp sms yolluyorum.düzeltilme ihtimali varsa daha kullanışlı olacaktır.

**Comment by rabilgic** [comment]
Çeviri ile ilgili hatalar dışındaki sorunları forum.miuiturkiye.net yada xiaomi.eu forumlarından yardım alabilirsiniz.
