### ISSUE TITLE
sim kart ayarları menüsü çeviri

### ISSUE THREAD

**Issue by gugukcu** [suat074/MA-XML-10-TURKISH#9]
vowifi açılmış mi8 de sim kart ayarları menüsünde "wlan kullanarak arama yap" seçeneği aktif halde iken alt satır ve satırın açtığı menü ingilizce kalmış.
kiilit ekranı parmak izi bölümünde gelişmiş ayarlar sondan bir önceki satır ingilizce kalmış.
geliştirici seçeneklerinde night mode kısmı, feature flasgs kısmı ve altındaki 3 satır kısım ile ağ kısmında bazı satırlar, çizimler kısmı son satır ingilizce kalmış.
çeviri için ayrıca teşekkürler.

**Comment by gugukcu** [comment]
Teşekkürler

Android için Outlook<https://aka.ms/ghei36>'u edinin

________________________________

**Comment by 404error01** [comment]
Hocam Mi 6x konum bulmuyor. Lütfen düzeltin

**Comment by rabilgic** [comment]
> Hocam Mi 6x konum bulmuyor. Lütfen düzeltin

Rom ile ilgili hata, geri bildirim ve isteklerinizi xiaomi.eu forumu üzerinden ilgili bölüme konu açarak bildirebilirsiniz. Teşekkürler.
